// 3474. Lexicographically Smallest Generated String

// You are given two strings, str1 and str2, of lengths n and m, respectively.

// A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

// If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
// If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
// Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

// Example 1:

// Input: str1 = "TFTF", str2 = "ab"

// Output: "ababa"

// Explanation:

// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.

// Return "ababa" since it is the lexicographically smaller string.

// Example 2:

// Input: str1 = "TFTF", str2 = "abc"

// Output: ""

// Explanation:

// No string that satisfies the conditions can be generated.

// Example 3:

// Input: str1 = "F", str2 = "d"

// Output: "a"

 

// Constraints:

// 1 <= n == str1.length <= 104
// 1 <= m == str2.length <= 500
// str1 consists only of 'T' or 'F'.
// str2 consists only of lowercase English characters.



class Solution {
    public String generateString(String str1, String str2) {
        int n = str1.length(), m = str2.length();
        int len = n + m - 1;
        char[] res = new char[len];
        for (int i = 0; i < len; i++) res[i] = '?';

        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    if (res[i + j] == '?' || res[i + j] == str2.charAt(j)) {
                        res[i + j] = str2.charAt(j);
                    } else {
                        return "";
                    }
                }
            }
        }

        for (int i = 0; i < len; i++) {
            if (res[i] == '?') res[i] = 'a';
        }

        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'F') {
                boolean same = true;
                for (int j = 0; j < m; j++) {
                    if (res[i + j] != str2.charAt(j)) {
                        same = false;
                        break;
                    }
                }
                if (same) {
                    boolean changed = false;
                    for (int j = m - 1; j >= 0; j--) {
                        int idx = i + j;
                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c != str2.charAt(j)) {
                                char old = res[idx];
                                res[idx] = c;
                                boolean ok = true;
                                for (int k = Math.max(0, idx - m + 1); k <= Math.min(idx, n - 1); k++) {
                                    if (str1.charAt(k) == 'T') {
                                        for (int t = 0; t < m; t++) {
                                            if (res[k + t] != str2.charAt(t)) {
                                                ok = false;
                                                break;
                                            }
                                        }
                                        if (!ok) break;
                                    }
                                }
                                if (ok) {
                                    changed = true;
                                    break;
                                }
                                res[idx] = old;
                            }
                        }
                        if (changed) break;
                    }
                    if (!changed) return "";
                }
            }
        }

        return new String(res);
    }
}